version: "3.6"
services:
  run-database:
    image: mongo
    container_name: "run-database"
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE_NAME
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
    volumes:
      - ./mongo-container/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-storage:/data/db
    ports:
      - 27017:27017
      - 27019:27019

  model-config:
    image: alpine
    container_name: "model-config-store"
    environment:
      - SRC_CLASSIFIER_DEF=/model-defs/classifiers.yaml
      - DST_CLASSIFIER_DEF=/models/defs/classifiers.yaml
    volumes:
      - ./search/defs:/model-defs/
      - model-definitions:/models/defs/
    command: ["/bin/sh", "-c", "cp $${SRC_CLASSIFIER_DEF} $${DST_CLASSIFIER_DEF} && ls -la /model-defs && ls -la /models/defs/"]

  model-search:
    build:
      context: search
    depends_on:
      - run-database
      - model-config
    environment:
      - MONGO_TRIALS_CONN=mongo://$MONGODB_ROOT_USERNAME:$MONGODB_ROOT_PASSWORD@run-database:27017/$MONGODB_DATABASE_NAME/jobs?authSource=admin
      - MONGO_WORKER_CONN=mongo://run-database:27017/$MONGODB_DATABASE_NAME/jobs?authSource=admin
      - CLASSIFIER_DEF=/models/defs/classifiers.yaml
      - OUTPUT_DIR=/models/
      - EXPERIMENT_NAME=${EXPERIMENT_NAME}
    volumes:
      - model-storage:/models/
      - model-definitions:/models/defs/:ro
    working_dir: /app
    command: ["/bin/bash", "-c", "python model_search.py & sleep 8 && PYTHONPATH=. hyperopt-mongo-worker --mongo=$${MONGO_TRIALS_CONN} --no-subprocesses"]

  tensorboard:
    image: tensorflow/tensorflow:latest-py3
    container_name: "tensorboard"
    depends_on:
      - model-search
    volumes:
      - model-storage:/models/
    environment:
      - OUTPUT_DIR=/models/
    ports:
      - 6006:6006
    command: ["/bin/bash", "-c", "tensorboard --logdir=$${OUTPUT_DIR}/logs/ --bind_all"]
volumes:
  mongo-storage:
  model-storage:
  model-definitions:
