apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  mongo-database-name: search-db
  mongo-root-username: root
  mongo-root-password: root

  mongo-uri: mongodb://mongo:27017
  mongo-hostname: mongo
  mongo-username: root
  mongo-password: root
  mongo-connection-string:
    mongodb://mongo:27017

  startup-script: |+
    db.createUser(
      {
        user: "$MONGO_INITDB_ROOT_USERNAME",
        pwd: "$MONGO_INITDB_ROOT_PASSWORD",
        roles: [
          {
            role: "readWrite",
            db: "$MONGO_INITDB_DATABASE"
          }
        ]
      }
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-configmap
data:
  mongo-username: root
  mongo-password: root
  mongo-database-name: search-db
  mongo-connection-string: mongo://root:root@mongo:27017/search-db/jobs?authSource=admin
  mongo-worker-connection: mongo://mongo:27017/search-db/jobs?authSource=admin
  model-output-dir: /models/
  experiment-name: search-test-01
  classifier-definitions: /model/defs/*.yaml
