apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  mongo-database-name: search-db
  mongo-root-username: root
  mongo-root-password: root

  mongo-uri: mongodb://mongo:27017
  mongo-hostname: mongo
  mongo-username: root
  mongo-password: root

  startup-script: |+
    db.createUser(
      {
        user: "$MONGO_INITDB_ROOT_USERNAME",
        pwd: "$MONGO_INITDB_ROOT_PASSWORD",
        roles: [
          {
            role: "readWrite",
            db: "$MONGO_INITDB_DATABASE"
          }
        ]
      }
    );
